version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo/examples/simple
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Initialize a root module.
          command: terraform init
      - run:
          name: Make sure the syntax is correct.
          command: terraform validate -var access_key=DUMMY -var secret_key=DUMMY -var support_iam_role_principal_arn=DUMMY
      - run:
          name: Make sure format wouldn't produce any diffs.
          command: terraform fmt -check=true -recursive
